general {
    hide_cursor = true
    grace = 1
    fade_in = true
}

background {
    monitor =
    path = /home/gav/.config/hypr/wallpaper.jpeg
    blur_passes = 6
    blur_size = 12
    brightness = 0.65
    contrast = 0.9
    vibrancy = 0.15
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = rgba(255,255,255,0.95)
    font_family = JetBrainsMono Nerd Font
    font_size = 86
    font_weight = 700
    position = 0,180
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A • %d %B %Y"
    color = rgba(255,255,255,0.65)
    font_family = JetBrainsMono Nerd Font
    font_size = 16
    position = 0,100
    halign = center
    valign = center
}

label {
    monitor =
    text = "lock in bruh"
    color = rgba(255,255,255,0.8)
    font_family = JetBrainsMono Nerd Font
    font_size = 14
    position = 0,40
    halign = center
    valign = center
}

input-field {
    monitor =

    size = 320,55

    outline_thickness = 2
    outer_color = rgba(255,255,255,0.35)
    inner_color = rgba(255,255,255,0.12)

    font_family = JetBrainsMono Nerd Font
    font_size = 14
    font_color = rgba(255,255,255,0.95)

    placeholder_text = "Enter Password"

    fade_on_empty = true
    dots_size = 0.125
    dots_spacing = 0.2
    dots_center = true

    position = 0,-60
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:5000] bash -c "echo $(cat /sys/class/power_supply/BAT0/capacity)%%"
    color = rgba(255,255,255,0.5)
    font_family = JetBrainsMono Nerd Font
    font_size = 12
    position = 0,-180
    halign = center
    valign = center
}
